version: "3"

services: 
    app:
        container_name: tucarreraperu
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        volumes: 
            - .:/usr/src/app
